version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - '0.0.0.0:8000'
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart:
      "always"
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '200'
    volumes:
      - ./mysite/database:/app/database
      - static_volume:/app/staticfiles
      - media_volume:/app/uploads


volumes:
  static_volume:
  media_volume: